version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/user-service
hooks:
  BeforeInstall:
    - location: aws-codedeploy-helpers/BeforeInstall.sh
      timeout: 1000
      runas: root
  AfterInstall:
    - location: aws-codedeploy-helpers/AfterInstall.sh
      timeout: 1000
      runas: root
  ApplicationStart:
    - location: aws-codedeploy-helpers/ApplicationStart.sh
      timeout: 1000
      runas: root
